name: Process Files

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload input files
        run: |
          mkdir artifacts
          cp "${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/names.txt" artifacts/
          cp "${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/location.txt" artifacts/
      shell: bash

      - name: Upload input files as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: input-files
          path: artifacts

      - name: Process files
        run: |
          # Get the uploaded files
          names_file="${{ github.workspace }}/artifacts/names.txt"
          location_file="${{ github.workspace }}/artifacts/location.txt"

          # Process the files as needed
          echo "Processing names file: $names_file"
          echo "Processing location file: $location_file"

          # Add your logic here to process the files
