name: Process Files

on:
  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload input files
      uses: actions/upload-artifact@v2
      with:
        name: input-files
        path: |
          names.txt
          location.txt

    - name: Run script
      run: |
        bash scripts/process_files.sh ${{ github.workspace }}/names.txt ${{ github.workspace }}/location.txt
