name: Environment Files Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment option"
        required: true
        default: "AWS"
        type: choice
        options:
          - AWS
          - Azure

jobs:
  environment-files-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment folder path
        id: set-env-folder-path
        run: echo "::set-output name=env-folder-path::./env/${{ github.event.inputs.env }}"

      - name: Print Environment Files
        run: |
          env_folder_path="${{ steps.set-env-folder-path.outputs.env-folder-path }}"

          # Check if the environment folder exists
          if [ -d "$env_folder_path" ]; then
            echo "Environment folder found: $env_folder_path"

            # Check if both names.txt and location.txt files exist
            if [ -f "$env_folder_path/names.txt" ] && [ -f "$env_folder_path/location.txt" ]; then
              echo "Both names.txt and location.txt files found in the environment folder."

              # Call the print_files.sh script and pass the env_folder_path as an argument
              bash scripts/print_files.sh "$env_folder_path"

            else
              echo "Either names.txt or location.txt file not found in the environment folder."
            fi

          else
            echo "Environment folder not found: $env_folder_path"
            exit 1
          fi
